/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.ClienteDAO;
import java.sql.SQLException;
import java.util.List;
import modelo.Cliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ClienteForm extends javax.swing.JFrame {

    private ClienteDAO clienteDao = new ClienteDAO();
    private List<Cliente> clientes;
    private Cliente clienteSelecionada;

    public ClienteForm() {
        initComponents();
        atualizarTabela();

        atualizarBotao(true);
        habilitarFomulario(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txf_cpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txf_sexo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txf_user_id = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_Cliente = new javax.swing.JTable();
        txf_nome = new javax.swing.JTextField();
        txf_Pesquisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_Pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("CPF");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        getContentPane().add(txf_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 360, -1));

        jLabel3.setText("Sexo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txf_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_sexoActionPerformed(evt);
            }
        });
        getContentPane().add(txf_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 350, -1));

        jLabel4.setText("Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txf_user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_user_idActionPerformed(evt);
            }
        });
        getContentPane().add(txf_user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 350, -1));

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        btn_Cancelar.setText("Cancelar");
        getContentPane().add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        tabela_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Sexo", "CPF", "Usuario"
            }
        ));
        jScrollPane1.setViewportView(tabela_Cliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 420, 110));

        txf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(txf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 330, -1));
        getContentPane().add(txf_Pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 260, -1));

        jLabel5.setText("Texto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        atualizarBotao(false);
        habilitarFomulario(true);
        txf_nome.requestFocus();
        clienteSelecionada = null;


    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void habilitarFomulario(boolean status) {
        txf_nome.setEnabled(status);
        txf_cpf.setEnabled(status);
        txf_sexo.setEnabled(status);
        txf_user_id.setEnabled(status);
        txf_cpf.setEnabled(status);
    }

    private void atualizarBotao(boolean status) {
        btn_alterar.setEnabled(status);
        btn_Excluir.setEnabled(status);
        btn_Pesquisar.setEnabled(status);
        btn_cadastrar.setEnabled(status);
        btn_Cancelar.setEnabled(!status);
        btn_Salvar.setEnabled(!status);
    }

    private void atualizarTabela() {
        try {
            clientes = clienteDao.buscarPeloNome(txf_Pesquisa.getText());
            DefaultTableModel model = (DefaultTableModel) tabela_Cliente.getModel();
            model.setNumRows(0);

            for (int i = 0; i < clientes.size(); i++) {
                Cliente cliente = clientes.get(i);
                model.addRow(new Object[]{cliente.getNome(), cliente.getCpf(), cliente.getSexo(), cliente.getUser_id()});

            }
        } catch (SQLException ex) {
            ex.printStackTrace();

        }

    }


    private void txf_user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_user_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_user_idActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed

        int linha = tabela_Cliente.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        clienteSelecionada = clientes.get(linha);
        try {
            clienteDao.remover(clienteSelecionada.getId());
            JOptionPane.showMessageDialog(null, "Cliente excluido");
            atualizarTabela();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        int linha = tabela_Cliente.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para alteração", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        atualizarBotao(false);
        habilitarFomulario(true);

        clienteSelecionada = clientes.get(linha);
        txf_nome.setText(clienteSelecionada.getNome());
        txf_sexo.setText(clienteSelecionada.getSexo());
        txf_cpf.setText(clienteSelecionada.getCpf());
        txf_user_id.setText(clienteSelecionada.getUser_id());

    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        atualizarBotao(true);
        habilitarFomulario(false);
        String nome = txf_nome.getText();
        String sexo = txf_sexo.getText();
        String cpf = txf_cpf.getText();
        String user_id = txf_user_id.getText();

        int codigo = 0;

        if (nome.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um nome ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (sexo.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um sexo ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }if (cpf.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um cpf ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (user_id.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um cpf ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (clienteSelecionada == null) {
            Cliente cliente = new Cliente(nome, sexo, cpf, user_id);

            try {
                clienteDao.adicionar(cliente);
                JOptionPane.showMessageDialog(null, "Cliente Cadastrado");
                txf_nome.setText("");
                txf_sexo.setText("");
                txf_cpf.setText("");
                txf_user_id.setText("");

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro na hora de inserir os dados", "Erro", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            clienteSelecionada.setNome(nome);
            clienteSelecionada.setSexo(sexo);
            clienteSelecionada.setCpf(cpf);
            clienteSelecionada.setUser_id(user_id);

            try {
                clienteDao.alterar(clienteSelecionada);
                JOptionPane.showMessageDialog(null, "Cliente alterado");
                atualizarTabela();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        }
        clienteSelecionada = null;
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void txf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_nomeActionPerformed

    private void txf_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_sexoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_Cliente;
    private javax.swing.JTextField txf_Pesquisa;
    private javax.swing.JTextField txf_cpf;
    private javax.swing.JTextField txf_nome;
    private javax.swing.JTextField txf_sexo;
    private javax.swing.JTextField txf_user_id;
    // End of variables declaration//GEN-END:variables
}
