/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.ProdutoDAO;
import java.io.FileWriter;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import modelo.Produto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.Usuario;

public class CompraForm extends javax.swing.JFrame {
int r = 0;
private Usuario usuario;

    /** Creates new form FormularioPrincipal */

    private ProdutoDAO produtoDAO = new ProdutoDAO();
    private List<Produto> produtos;
    private Produto produtoSelecionada;

    public CompraForm() {
        initComponents();
        atualizarTabela();

        atualizarBotao(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_Produto = new javax.swing.JTable();
        txf_Pesquisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_Pesquisar = new javax.swing.JButton();
        btn_Comprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela_Produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Preço", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(tabela_Produto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 430, 190));
        getContentPane().add(txf_Pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 260, -1));

        jLabel5.setText("Texto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 90, -1));

        btn_Comprar.setText("Comprar");
        btn_Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ComprarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void atualizarBotao(boolean status) {
        btn_Pesquisar.setEnabled(status);
    }

    private void atualizarTabela() {
        try {
            produtos = produtoDAO.buscarPeloNome(txf_Pesquisa.getText());
            DefaultTableModel model = (DefaultTableModel)tabela_Produto.getModel();
            model.setNumRows(0);

            for (int i = 0; i < produtos.size(); i++) {
                Produto produto = produtos.get(i);
                model.addRow(new Object[]{produto.getNome(), produto.getPreco(), produto.getCategoria_id()});

            }
        } catch (SQLException ex) {
            ex.printStackTrace();

        }

    }


    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void btn_ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ComprarActionPerformed
                                               
        int linha = tabela_Produto.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um produto para comprar", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
       
       produtoSelecionada = produtos.get(linha);
       String nome = produtoSelecionada.getNome();
       String categoria_id = produtoSelecionada.getCategoria_id();
       int categoria_id_int = parseInt(categoria_id);
       String  preco =  produtoSelecionada.getPreco(); 
       LocalDate localDate = LocalDate.now(ZoneId.of("GMT+03:00"));
       String categoria_name = "";
       System.out.print(categoria_id);
       
       if(categoria_id_int == 1){
            categoria_name = "Instrumento de corda";
       }
       if(categoria_id_int == 2){
            categoria_name = "Instrumento de sopro";
       }
       if(categoria_id_int == 3){
           categoria_name = "Instrumento de percussão";
       }
       if(categoria_id_int == 4){
            categoria_name  = "Instrumento Eletrofone";
       }
       
        try{
            r++;
            FileWriter Writer = new FileWriter("/home/horus/Área de Trabalho/RelatóriosPOO1/nota"+r+".txt", true);
            Writer.write("Nome: "+nome+"\n Preço: " +preco+ "\n Categoria: "+categoria_name+ "\n Dia da compra: "+localDate+"\n-----------------");
            Writer.write(System.getProperty("line.separator"));
            Writer.close();
            JOptionPane.showMessageDialog(null, "Prontinho!");
            setVisible(false);
            
        }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, "Houve algum problema ao gerar nota!");
        System.out.print(e);
    }
      
    }//GEN-LAST:event_btn_ComprarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Comprar;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_Produto;
    private javax.swing.JTextField txf_Pesquisa;
    // End of variables declaration//GEN-END:variables
}
