/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.FuncionarioDAO;
import java.sql.SQLException;
import java.util.List;
import modelo.Funcionario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FuncionarioForm extends javax.swing.JFrame {

    private FuncionarioDAO funcionarioDao = new FuncionarioDAO();
    private List<Funcionario> funcionarios;
    private Funcionario funcionarioSelecionada;

    public FuncionarioForm() {
        initComponents();
        atualizarTabela();

        atualizarBotao(true);
        habilitarFomulario(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txf_cpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txf_sexo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txf_cargo = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_Funcionario = new javax.swing.JTable();
        txf_nome = new javax.swing.JTextField();
        txf_Pesquisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_Pesquisar = new javax.swing.JButton();
        txf_salario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setText("CPF");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txf_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_cpfActionPerformed(evt);
            }
        });
        getContentPane().add(txf_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 360, -1));

        jLabel3.setText("Sexo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(txf_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 350, -1));

        jLabel4.setText("Cargo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txf_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_cargoActionPerformed(evt);
            }
        });
        getContentPane().add(txf_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 350, -1));

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        btn_Cancelar.setText("Cancelar");
        getContentPane().add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        tabela_Funcionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Cpf", "Sexo", "Cargo", "Salario"
            }
        ));
        jScrollPane1.setViewportView(tabela_Funcionario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 420, 110));

        txf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(txf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 330, -1));
        getContentPane().add(txf_Pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 260, -1));

        jLabel5.setText("Texto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 90, -1));

        txf_salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_salarioActionPerformed(evt);
            }
        });
        getContentPane().add(txf_salario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 350, -1));

        jLabel6.setText("Salário");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        atualizarBotao(false);
        habilitarFomulario(true);
        txf_nome.requestFocus();
        funcionarioSelecionada = null;


    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void habilitarFomulario(boolean status) {
        txf_nome.setEnabled(status);
        txf_cpf.setEnabled(status);
        txf_sexo.setEnabled(status);
        txf_cargo.setEnabled(status);
        txf_salario.setEnabled(status);

    }

    private void atualizarBotao(boolean status) {
        btn_alterar.setEnabled(status);
        btn_Excluir.setEnabled(status);
        btn_Pesquisar.setEnabled(status);
        btn_cadastrar.setEnabled(status);
        btn_Cancelar.setEnabled(!status);
        btn_Salvar.setEnabled(!status);
    }

    private void atualizarTabela() {
        try {
            funcionarios = funcionarioDao.buscarPeloNome(txf_Pesquisa.getText());
            DefaultTableModel model = (DefaultTableModel) tabela_Funcionario.getModel();
            model.setNumRows(0);

            for (int i = 0; i < funcionarios.size(); i++) {
                Funcionario funcionario = funcionarios.get(i);
                model.addRow(new Object[]{funcionario.getNome(), funcionario.getSexo(), funcionario.getCpf(), funcionario.getCargo(), funcionario.getSalario(), });

            }
        } catch (SQLException ex) {
            ex.printStackTrace();

        }

    }


    private void txf_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_cargoActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed

        int linha = tabela_Funcionario.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma funcionario", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        funcionarioSelecionada = funcionarios.get(linha);
        try {
            funcionarioDao.remover(funcionarioSelecionada.getId());
            JOptionPane.showMessageDialog(null, "Funcionario excluida");
            atualizarTabela();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        int linha = tabela_Funcionario.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma funcionario para alteração", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        atualizarBotao(false);
        habilitarFomulario(true);

        funcionarioSelecionada = funcionarios.get(linha);
        txf_nome.setText(funcionarioSelecionada.getNome());
        txf_sexo.setText(funcionarioSelecionada.getSexo());
        txf_cargo.setText(funcionarioSelecionada.getCargo());
        txf_cpf.setText(funcionarioSelecionada.getSalario());
        txf_cpf.setText(funcionarioSelecionada.getCpf());

    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        atualizarBotao(true);
        habilitarFomulario(false);
        String nome = txf_nome.getText();
        String cpf = txf_cpf.getText();
        String sexo = txf_sexo.getText();
        String cargo= txf_cargo.getText();
        String salario = txf_salario.getText();
        int codigo = 0;

        if (nome.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um nome ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cpf.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um cpf ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (sexo.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um sexo ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }if (cargo.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um cargo ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }if (salario.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um salario ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (funcionarioSelecionada == null) {
            Funcionario funcionario = new Funcionario(nome, cpf, sexo, cargo, salario);

            try {
                funcionarioDao.adicionar(funcionario);
                JOptionPane.showMessageDialog(null, "Funcionario Cadastrada");
                txf_nome.setText("");
                txf_cpf.setText("");
                txf_sexo.setText("");
                txf_cargo.setText("");
                txf_salario.setText("");

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro na hora de inserir os dados", "Erro", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            funcionarioSelecionada.setNome(nome);
            funcionarioSelecionada.setCpf(cpf);
            funcionarioSelecionada.setSexo(sexo);
            funcionarioSelecionada.setCargo(cargo);
            funcionarioSelecionada.setSalario(salario);
            


            try {
                funcionarioDao.alterar(funcionarioSelecionada);
                JOptionPane.showMessageDialog(null, "Funcionario alterado");
                atualizarTabela();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        }
        funcionarioSelecionada = null;
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void txf_salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_salarioActionPerformed

    private void txf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_nomeActionPerformed

    private void txf_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_cpfActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_Funcionario;
    private javax.swing.JTextField txf_Pesquisa;
    private javax.swing.JTextField txf_cargo;
    private javax.swing.JTextField txf_cpf;
    private javax.swing.JTextField txf_nome;
    private javax.swing.JTextField txf_salario;
    private javax.swing.JTextField txf_sexo;
    // End of variables declaration//GEN-END:variables
}
