/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.UsuarioDAO;
import java.sql.SQLException;
import java.util.List;
import modelo.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class UsuarioForm extends javax.swing.JFrame {

    private UsuarioDAO usuarioDao = new UsuarioDAO();
    private List<Usuario> usuarios;
    private Usuario usuarioSelecionado;

    public UsuarioForm() {
        initComponents();
        atualizarTabela();

        atualizarBotao(true);
        habilitarFomulario(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txf_login = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txf_senha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txf_nivel = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_Usuario = new javax.swing.JTable();
        txf_nome = new javax.swing.JTextField();
        txf_Pesquisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_Pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setText("Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        getContentPane().add(txf_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 370, -1));

        jLabel3.setText("Senha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(txf_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 360, -1));

        jLabel4.setText("Nivel");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txf_nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nivelActionPerformed(evt);
            }
        });
        getContentPane().add(txf_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 360, -1));

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 90, -1));

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        btn_Cancelar.setText("Cancelar");
        getContentPane().add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        tabela_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Login", "Senha", "Nivel"
            }
        ));
        jScrollPane1.setViewportView(tabela_Usuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 430, 110));

        txf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(txf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 340, -1));
        getContentPane().add(txf_Pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 280, -1));

        jLabel5.setText("Texto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        atualizarBotao(false);
        habilitarFomulario(true);
        txf_nome.requestFocus();
        usuarioSelecionado = null;


    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void habilitarFomulario(boolean status) {
        txf_nome.setEnabled(status);
        txf_login.setEnabled(status);
        txf_senha.setEnabled(status);
        txf_nivel.setEnabled(status);

    }

    private void atualizarBotao(boolean status) {
        btn_alterar.setEnabled(status);
        btn_Excluir.setEnabled(status);
        btn_Pesquisar.setEnabled(status);
        btn_cadastrar.setEnabled(status);
        btn_Cancelar.setEnabled(!status);
        btn_Salvar.setEnabled(!status);
    }

    private void atualizarTabela() {
        try {
            usuarios = usuarioDao.buscarPeloNome(txf_Pesquisa.getText());
            DefaultTableModel model = (DefaultTableModel) tabela_Usuario.getModel();
            model.setNumRows(0);

            for (int i = 0; i < usuarios.size(); i++) {
                Usuario usuario = usuarios.get(i);
                model.addRow(new Object[]{usuario.getNome(), usuario.getLogin(), usuario.getSenha(), usuario.getNivel()});

            }
        } catch (SQLException ex) {
            ex.printStackTrace();

        }

    }


    private void txf_nivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_nivelActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed

        int linha = tabela_Usuario.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um usuario", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        usuarioSelecionado = usuarios.get(linha);
        try {
            usuarioDao.remover(usuarioSelecionado.getId());
            JOptionPane.showMessageDialog(null, "Usuario excluido");
            atualizarTabela();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        int linha = tabela_Usuario.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um usuario para alteração", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        atualizarBotao(false);
        habilitarFomulario(true);

        usuarioSelecionado = usuarios.get(linha);
        txf_nome.setText(usuarioSelecionado.getNome());
        txf_senha.setText(usuarioSelecionado.getSenha());
        txf_nivel.setText(usuarioSelecionado.getNivel());
        txf_login.setText(usuarioSelecionado.getLogin());

    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        atualizarBotao(true);
        habilitarFomulario(false);
        String nome = txf_nome.getText();
        String login= txf_login.getText();
        String senha = txf_senha.getText();
        String nivel = txf_nivel.getText();

        if (nome.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um nome ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (login.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um login ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (senha.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe uma senha ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }if (nivel.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um nivel ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;

        }
        if (usuarioSelecionado == null) {
            Usuario usuario = new Usuario(nome, login, senha, nivel);

            try {
                usuarioDao.adicionar(usuario);
                JOptionPane.showMessageDialog(null, "Usuario Cadastrado");
                txf_nome.setText("");
                txf_login.setText("");
                txf_senha.setText("");
                txf_nivel.setText("");

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro na hora de inserir os dados", "Erro", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            usuarioSelecionado.setNome(nome);
            usuarioSelecionado.setLogin(login);
            usuarioSelecionado.setSenha(senha);
            usuarioSelecionado.setNivel(nivel);
            try {
                usuarioDao.alterar(usuarioSelecionado);
                JOptionPane.showMessageDialog(null, "Usuario alterado");
                atualizarTabela();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        }
        usuarioSelecionado = null;
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void txf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_nomeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_Usuario;
    private javax.swing.JTextField txf_Pesquisa;
    private javax.swing.JTextField txf_login;
    private javax.swing.JTextField txf_nivel;
    private javax.swing.JTextField txf_nome;
    private javax.swing.JTextField txf_senha;
    // End of variables declaration//GEN-END:variables
}
